plugins {
    id 'java'
    alias(libs.plugins.spring.boot) apply false
    alias(libs.plugins.spring.dependency.management) apply false
}

allprojects {
    group = 'com.bearify'
    version = '0.1.0-SNAPSHOT'
}

def catalog = libs

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    plugins.withId('org.springframework.boot') {
        tasks.named('bootRun').configure {
            workingDir = rootProject.projectDir
        }
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << '-parameters'
    }

    dependencies {
        testRuntimeOnly catalog.junit.platform.launcher
    }

    tasks.named('test') {
        useJUnitPlatform()
    }

    repositories {
        mavenCentral()
        maven { url = uri("https://maven.lavalink.dev/releases") }
        maven { url = uri("https://maven.lavalink.dev/snapshots") }
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:${catalog.versions.spring.boot.get()}"
        }
    }
}
