spring:
  application:
    name: bearify-player
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}

player:
  id: ${PLAYER_ID:player-1}

discord:
  token: ${DISCORD_PLAYER_TOKEN}
  guild-id: ${DISCORD_GUILD_ID}

music-player:
  previous-restart-threshold: 3s
  seek-short-default: 10s
  seek-long-default: 30s
  seek-track-length-threshold: 5m
  engine:
    youtube:
      refresh-token: ${YOUTUBE_REFRESH_TOKEN:}
