spring:
  application:
    name: bearify-controller
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}

discord:
  token: ${DISCORD_CONTROLLER_TOKEN}
  guild-id: ${DISCORD_GUILD_ID:}  # leave blank for global commands in production
  activity:
    type: PLAYING
    text: "Playing with Honey"
